name = "realthx1/luaulog"
version = "0.2.0"
description = "Fast and easy-to-use logging library for Roblox"
authors = ["realthx1"]
repository = "https://github.com/realthx1/luaulog"
license = "MIT"
includes = ["src/**/*", "pesde.toml", "README.md", "LICENSE", ".luaurc", "docs"]

[target]
environment = "roblox"
build_files = ["src"]
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
rojo = { name = "pesde/rojo", version = "^7.6.0", target = "lune" }
selene = { name = "pesde/selene", version = "^0.29.0+toolchainlib.1", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.3.0", target = "lune" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.55.0", target = "lune" }

[engines]
lune = "^0.10.4"
pesde = "^0.7.1"
