[package]
name = "realthx1/luaulog"
version = "0.2.0"
description = "Easy-to-use and fast logging library for Roblox"
license = "MIT"
authors = ["realthx1"]
repository = "https://github.com/realthx1/luaulog/"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
	"default.project.json",
	"src",
	"src/*",
	"src/**/*",
	"wally.toml",
	"wally.lock",
	"README.md",
	"LICENSE",
	".luaurc",
	"docs",
]
exclude = ["*"]

[dependencies]
